### ISSUE TITLE
Unable to launch when plugin is enabled

### ISSUE THREAD

**Issue by gizlonk** [Goobwabber/MultiQuestensions#13] opened 2021-11-18 13:59 UTC
First off - I know there are other reports - but I suspect you will not get the feedback you need there in a timely manner, and so I am logging my own. 

I am attaching the three tombstone_** files I found, as all the crashes are caused by this issue. 

[tombstones.zip](https://github.com/Goobwabber/MultiQuestensions/files/7563283/tombstones.zip)

I am able and willing to provide any logs that may be required. I can also test changes, ect. Let me know if there is any way I can help here. 

Steps to reproduce the issue:

1. Install BeatTogether mod on quest from here - https://github.com/pythonology/BeatTogether.Quest
2. Install MultiQuestensions mod on quest from here - https://github.com/Goobwabber/MultiQuestensions/releases 
3. Launch Modded Multiplayer, host a game
4. Friend joins game that I am hosting
5. Select custom song - friend download the song from BeatSaver automatically thanks to the plugin (that works just fine, it seems)
6. Round launches, but then the game crashes for the host only - friend is still in lobby at this stage, and stays there till they quit
7. From this point on, launching the game with the MultiQuestensions mod enabled, the game crashes. Disabling the mod via BMBF allows the game to launch. Re-enabling it seems to start the process over again (it launches, but crashes at step 6, again).

Quick facts:

- I am on BeatSaber version 1.17.1 (downgraded from latest)
- I used BMBF to mod the game
- MultiQuestensions v0.1.0
- BeatTogether v1.3.0

Again, I am happy to assist in any way I can. Please feel free to rely on me for speedy responses and detailed information back. My TZ is SAST.

**Comment by michael-r-elp** [comment] 2021-11-18 16:32
This seems to be one of the main crashes some people have that I have yet to find the cause of, as it's not something everyone experiences. 

It might help to toggle some mods off, if others are enabled and installed, and in extreme cases a full re-install and re-modding of Beat Saber might help. 
Otherwise there's not much I can do for now, though a logcat would still be nice to see, just so I can check if it always happens at around the same point for everyone.

I might get back to you if I ever have any potential idea on the cause though.

**Comment by michael-r-elp** [comment] 2021-11-18 19:08
Ok, I finally gotten some time to talk to someone who knows a bit more about things, following some of his advice I made a few minor code changes, could you please test if this possible works better?

[multiquestensions_v0.1.1-patch (UNZIP FOR QMOD).zip](https://github.com/Goobwabber/MultiQuestensions/files/7565382/multiquestensions_v0.1.1-patch.UNZIP.FOR.QMOD.zip)

**Comment by gizlonk** [comment] 2021-11-18 20:05
It was the tricksaber and/or "mod version" mod. 

I tried the v0.1.1 patch above - and it still failed. I then followed your advice and disabled, and deleted the tricksaber mod I had enabled, and the "mod version" mod, and then I was able to launch the game, start a multiplayer game, and have it work completely as expected. 

Apologies for not doing that earlier - but hopefully if someone else has this issue, and has those mods enabled - we now know it breaks stuff. 

I am happy to provide more logs or any other info if you need it. Do you recommend I go back to v0.1.0 or stay where I am for now?

Let me know if I can buy you a coffee somehow.

**Comment by michael-r-elp** [comment] 2021-11-18 21:26
Good to know, I'll keep TrickSaber in mind. 

You might possibly want to report the issue on the tricksaber repository, though given how finnicky it is with crashes right now, it might be worth waiting for the next big mod release and checking again to see if stuff is hopefully more stable then

I'll be closing the issue for now in that case.

Anyways, have fun playing.

PS: Up to you if you want to buy me a coffee

**Closed as completed by michael-r-elp** 2021-11-18 21:26 UTC
Labels: bug, question
